### ISSUE TITLE
README update

### ISSUE THREAD

**Issue by tiendu** [jfmrod/MAPseq#10]
Hi there,

I think the README is a bit outdated. Some people installing the software through git clone might have the problem with the eutils if the package subversion is not installed. So an update of README with additional notes would be helpful.

Regards,

Tien Du

**Comment by jfmrod** [comment]
Dear Tien Du,

Thanks a lot for your feedback and help in improving mapseq!
I've modified the readme to include the requirement for subversion (and corresponding command for installing it on ubuntu systems).

Best regards,

João
