### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by gkapatai** [jfmrod/MAPseq#11]
Hi, I tried installing the latest version from the repo using the instructions in your README file but i am getting a compilation error... After installing dependencies I run:
git clone https://github.com/jfmrod/MAPseq.git
cd MAPseq
./setup.sh
./bootstrap
./configure
make
make install

This runs ok up to ./configure. When running make I get this error:
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -DINCLUDEPATH=\"/usr/local/lib/eutils/include\" -DMODULEPATH=\"/usr/local/lib/eutils\" -DWEBHTMLPATH=\"/usr/local/share/eutils/webhtml\" -O3 -pthread -D_GNU_SOURCE -D_DEFAULT_SOURCE -MT ernd.lo -MD -MP -MF .deps/ernd.Tpo -c ernd.cpp  -fPIC -DPIC -o .libs/ernd.o
ernd.cpp: In destructor ‘ernd::~ernd()’:
ernd.cpp:164:32: error: ‘hCryptAlg’ was not declared in this scope
   BCryptCloseAlgorithmProvider(hCryptAlg, 0);
                                ^~~~~~~~~
ernd.cpp:164:3: error: ‘BCryptCloseAlgorithmProvider’ was not declared in this scope
   BCryptCloseAlgorithmProvider(hCryptAlg, 0);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
Makefile:1102: recipe for target 'ernd.lo' failed
I would try and debug a bit more but my knowledge of C++ is very limited. 
Many thanks.

**Comment by jmcelh** [comment]
Hi Joao, I am also facing the same sort of issue as gka reported (and am likewise not particularly familiar with C++), however, my error occurs at "make" (please find below result of the command).  I thought it may be a missing dependency and installed bcrypt but to no avail. if you could point me in the right direction to address this I would be most grateful.

Best wishes,

James

mac@mac-G551JM:~/Dropbox/masdar_institute/biofouling_project/Metagenomics/MapSeq/bin/MAPseq$ make
make  all-recursive
make[1]: Entering directory `/home/mac/Dropbox/masdar_institute/biofouling_project/Metagenomics/MapSeq/bin/MAPseq'
Making all in libs/eutils
make[2]: Entering directory `/home/mac/Dropbox/masdar_institute/biofouling_project/Metagenomics/MapSeq/bin/MAPseq/libs/eutils'
make  all-am
make[3]: Entering directory `/home/mac/Dropbox/masdar_institute/biofouling_project/Metagenomics/MapSeq/bin/MAPseq/libs/eutils'
depbase=`echo ernd.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/bash ./libtool  --tag=CXX   --mode=compile g++ -std=gnu++11 -DHAVE_CONFIG_H -I.    -DINCLUDEPATH='"/usr/local/lib/eutils/include"' -DMODULEPATH='"/usr/local/lib/eutils"' -DWEBHTMLPATH='"/usr/local/share/eutils/webhtml"' -O3 -pthread  -MT ernd.lo -MD -MP -MF $depbase.Tpo -c -o ernd.lo ernd.cpp &&\
	mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -std=gnu++11 -DHAVE_CONFIG_H -I. -DINCLUDEPATH=\"/usr/local/lib/eutils/include\" -DMODULEPATH=\"/usr/local/lib/eutils\" -DWEBHTMLPATH=\"/usr/local/share/eutils/webhtml\" -O3 -pthread -MT ernd.lo -MD -MP -MF .deps/ernd.Tpo -c ernd.cpp  -fPIC -DPIC -o .libs/ernd.o
ernd.cpp: In destructor 'ernd::~ernd()':
ernd.cpp:164:32: error: 'hCryptAlg' was not declared in this scope
   BCryptCloseAlgorithmProvider(hCryptAlg, 0);
                                ^
ernd.cpp:164:44: error: 'BCryptCloseAlgorithmProvider' was not declared in this scope
   BCryptCloseAlgorithmProvider(hCryptAlg, 0);
                                            ^
make[3]: *** [ernd.lo] Error 1
make[3]: Leaving directory `/home/mac/Dropbox/masdar_institute/biofouling_project/Metagenomics/MapSeq/bin/MAPseq/libs/eutils'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/home/mac/Dropbox/masdar_institute/biofouling_project/Metagenomics/MapSeq/bin/MAPseq/libs/eutils'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/mac/Dropbox/masdar_institute/biofouling_project/Metagenomics/MapSeq/bin/MAPseq'
make: *** [all] Error 2

**Comment by jfmrod** [comment]
Thanks for reporting this. Just fixed it a few days ago.
