### ISSUE TITLE
Installation Issue #2

### ISSUE THREAD

**Issue by tonyjhlam** [jfmrod/MAPseq#12]
Getting an error following installation protocol:

> In file included from ./eutils/emain.h:4:0,
>                  from mapseq.cpp:1:
> ./eutils/eutils.h:6:28: fatal error: eutils-config.h: No such file or directory
>   #include "eutils-config.h"
>                             ^
> compilation terminated.

**Comment by jfmrod** [comment]
This file should be generated by the ./bootstrap and ./configure commands.
If you ran those commands and it still didn't fix it, let me know what system you are trying to compile in.
