### ISSUE TITLE
Didn't find binary package file and libeutills-1.0.so error

### ISSUE THREAD

**Issue by rondonbio** [jfmrod/MAPseq#14]
Hi! I use your software and like it very much.
Just tried to install in my machine a few times with no success. 
First I tried the the binary package, but didn't find the package file from the git clone download.
Then I installed from source, playing those commands (ubuntu 19.04):

```
sudo apt install build-essential wget subversion git libncurses5-dev libtool
sudo ./setup.sh 
sudo ./bootstrap 
sudo apt install autotools-dev
sudo apt install autoconf
sudo ./configure
sudo make
sudo make install
```

But when I run mapseq, the screen print this out:
mapseq: error while loading shared libraries: libeutils-1.0.so: cannot open shared object file: No such file or directory.
Can you help me?

Thanks in advance,
Rondon Neto

**Comment by rondonbio** [comment]
Just found the binary package here in github releases, but it is not at the cloned files.

**Comment by jfmrod** [comment]
Hi Rondon,
Great to know that you are using and like mapseq! 

I was just about to give you a link to the page. In case anyone else has the same problem:
The binary package is not available through git clone but on the "releases" section of the mapseq github page, the link provided by github it is a bit hidden but on the top of the main page in the small menu just above the "clone" button. Here is a direct link https://github.com/jfmrod/MAPseq/releases .

In any case, you seem to almost have a self compiled mapseq binary. The error you are getting is mapseq saying it can't find the ".so" file. Probably the libeutils-1.0.so file is getting installed in a directory where the system doesn't look for it automatically. When you run "sudo make install" it will show you in one of the lines. Usually it is in "/usr/local/lib"

One way to tell the system where to find libeutils for mapseq, is to type in your linux shell

export LD_LIBRARY_PATH="/usr/local/lib"

You will need to add that line to your .bashrc or .bash_profile in your home directory so you don't have to run it every time before running mapseq. I'll add this information into the README and see if there is a way to have the install work without that.
