### ISSUE TITLE
Visualization with Krona

### ISSUE THREAD

**Issue by sarah872** [jfmrod/MAPseq#16]
Is there a way to visualize the output with krona?

**Comment by jfmrod** [comment]
Hi,
It seems like it should be relatively easy to get the MAPseq data in Krona. Krona has an option to read text data. Using the -otucounts option from MAPseq for the analyzed output will give you counts for the different levels. For example:

0 1 Bacteria;Bacteroidetes 7586
0 1 Bacteria;Firmicutes 2150
0 1 Bacteria;Proteobacteria 112
0 1 Bacteria;PHY_Coriobacteriia 7
0 1 Bacteria;Actinobacteria 4
0 1 Bacteria;Fusobacteria 1

By putting the counts as the first column, and replacing the semi colon ";" with a tab, you should be able to import the data unto the Krona visualizer.

I might include it as an option in a next version of MAPseq.

**Comment by sarah872** [comment]
great. so something like this would do the trick:
```
ktImportText <(grep -v "^#" mseq.otutable | awk '{print $2,$1}' | sed 's/;/\t/g')
```

**Comment by jfmrod** [comment]
That would almost work. In the otutable file you have all counts at all levels and for the two different "taxonomies" (NCBI taxonomy and "OTU" taxonomy). To distinguish between the different levels and taxonomies you can use the first two fields. The first one, indicates if it is the NCBI taxonomy (0) or OTU "taxonomy" (1) and the second is the level from (0 to 5 on the OTU taxonomy and 0 to 6 on the NCBI taxonomy).

So if you wanted to get the NCBI taxonomy (0) at the Phylum level (1). You could change your awk command to: awk '$1==0 && $2==1 { print $4,$3 }'

**Comment by marcadella** [comment]
I guess it is a little bit more complicated than that, isn't it ? Let's say I want to display down to level 6, but there is a hit in level 5 (but not 6). This should be displayed as "other" in the level 6 of the krona chart. If I simply filter with `awk '$1==0 && $2==6` I would miss all those "others".
Note sure my explanation was very clear though...

**Comment by jfmrod** [comment]
Yes, you are right. I guess Krona might need the missing counts at higher levels to be explicitly categorised as unclassified/unmapped. I have an updated (not yet released) version of the otucounts function that reports the "missing counts" as either "NOT_IN_REF" or "AMBIGUOUS", which clarifies why the reads could not be mapped: either not have a close enough representative in the reference set, or they matched more than one OTU at that level.

If you are interested I'll add that, and a Krona export function to mapseq so it should just work out of the box.

**Comment by marcadella** [comment]
That would be great!
