### ISSUE TITLE
Missing db fasta file

### ISSUE THREAD

**Issue by hjruscheweyh** [jfmrod/MAPseq#17]
Hi Joao

I just the alpha release of mapseq 2 a try. And running mapseq out of the box fails

```
 ./mapseq test.fasta
# mapseq v2.0alpha (Feb 26 2020)
E! Fri Jun 12 11:54:08 2020 [] mapseq.cpp:3143 void loadSequences(eseqdb&, int): !error!: fasta db not found: share/mapseq/mapref-2.2.fna
```

The db in the archive is named differently. This command works

```
./mapseq test.fasta share/mapseq/mapref-2.2b.fna
```

Is this the correct database?

**Comment by jfmrod** [comment]
Hi Hans,

Thanks for the heads up. I will fix that right away.

Yes mapref-2.2b.fna is the most current reference. But if you want mapseq to classify OTUs or NCBI taxonomy you need to provide it with the otutax or ncbitax files after the mapref-2.2b.fna file:
./mapseq test.fasta share/mapseq/mapref-2.2b.fna share/mapseq/mapref-2.2b.fna.ncbitax

or

./mapseq test.fasta share/mapseq/mapref-2.2b.fna share/mapseq/mapref-2.2b.fna.otutax

or even both taxonomies together:
./mapseq test.fasta share/mapseq/mapref-2.2b.fna share/mapseq/mapref-2.2b.fna.otutax  share/mapseq/mapref-2.2b.fna.ncbitax
