### ISSUE TITLE
Add MAPseq to bioconda

### ISSUE THREAD

**Issue by colinbrislawn** [jfmrod/MAPseq#19]
Being able to install MAPseq as a [bioconda package](https://github.com/bioconda/bioconda-recipes) would be awesome! 🐍 📦 

(Vsearch is on available on bioconda, and this has aided it's adoption. [![image](https://anaconda.org/bioconda/vsearch/badges/downloads.svg)](https://anaconda.org/bioconda/vsearch))

**Comment by jfmrod** [comment]
Good suggestion, thanks! Just finished adding the recipe. Its waiting on the bioconda maintainers for approval.

**Comment by colinbrislawn** [comment]
Thank you @jfmrod for building this. I'll look forward to trying it!

Hey @mestaki, check this out!
