### ISSUE TITLE
Segmentation fault when using '-otutable'

### ISSUE THREAD

**Issue by evilvenom** [jfmrod/MAPseq#24]
Whenever I use the argument '-otutable' it throws me "Segmentation Fault" error. Can you please help me with this?

**Comment by jfmrod** [comment]
Hi! Sure, can you tell me which version of mapseq you are using and how or where you downloaded installed it from: bioconda, compiled from source or the binaries available on github.

**Comment by evilvenom** [comment]
@jfmrod Thanks for the response, I am using MAPseq v2.0.1alpha and I compiled it from the release binaries available on github.

Link for reference: https://github.com/jfmrod/MAPseq/releases/tag/2.0.1alpha

**Comment by jfmrod** [comment]
can you tell me the operating system and version you are running on, as well as the command you are running, does it always give a segmentation fault even if you just call "mapseq" without commands? If it only crashes when trying to analyse some data that can include a small file with enough lines to reproduce the error.

**Comment by evilvenom** [comment]
It works flawlessly without OTU table. Just wanted to update you on something, it was probably something with the input database, as of today, all the functions worked well. Thanks for your help!

**Comment by jfmrod** [comment]
Great! if you have an idea what was wrong with the input, I could add some checks to prevent the segmentation fault and give a more useful error message.
