### ISSUE TITLE
Certain taxa clutters strict column counts in output

### ISSUE THREAD

**Issue by emrobe** [jfmrod/MAPseq#5]
Hi,

I'm making some scripts to convert the output (with confidences) to different visualization tools, such as KronaTools++
Certain taxonomy classifications (B16S, ...) are written with a prepended "\t" in the output, which breaks the assumption that each classification strictly consists of 3 columns pr. level after column 13 [empty]. I have made a quick fix for this for my self, but just thought you should know in case this is a bug that should be fixed in the output.

**Comment by jfmrod** [comment]
Hi.
Thanks for the heads up. Currently there is indeed an empty field (in between two "tabs") separating the taxonomic classification outputs, as well as between the alignment information and the first taxonomic classification. The idea is to provide a way to signal the start of the different taxonomic classifications without having to hard code the number of fields (which is usually different for every taxonomy).
