### ISSUE TITLE
How to define the cutoff values in the taxonomy file?

### ISSUE THREAD

**Issue by TurbulentCupcake** [jfmrod/MAPseq#6]
I'm kinda confused about how the cutoffs must be defined in the taxonomy files. What do the numbers on either side of the double colons mean?

**Comment by jfmrod** [comment]
Hi, 
The numbers on the taxonomy files are identity cutoffs and a scaling parameter. For example:
#cutoff: 0.00:0.08 0.70:0.35 0.70:0.35 0.70:0.35 0.80:0.25 0.92:0.08 0.95:0.05
Each pair of numbers (separated by the colon ":") corresponds to a different taxonomic level.
In the species level: 0.95:0.05, indicates that below 0.95 (95% identity) the confidence (based on identity) assignment will be 0.0. The confidence above 0.95 is given by: confidence(id)=(id - 0.95 + 0.02)/0.05. Where 0.05 is the scaling parameter. So for example if the identity for the top hit was 96%, the identity confidence would be: confidence(0.96)= (0.96-0.95+0.02)/0.05 = 0.6 . Please note that the final confidence (combined) is the minimum of the identity confidence and the score confidence. In simple terms, the score confidence measures the difference in score between the top hit and the second best hits.
