### ISSUE TITLE
Some sequences without taxonomy assignment output

### ISSUE THREAD

**Issue by biofuture** [jfmrod/MAPseq#7]
Dear Author

I extracted V3V4 from Silva database and use that as the reference database in MAPseq.  I removed those sequences with length over 600 bps in the database.  

After I annotate my representative sequences with MAPseq, I found that a portion of the sequences were not annotated at all (200 sequences in 4100 were not annotated). 

What does this mean? Does this mean that these sequences were unknown? Why MAPseq does not output the results for those sequences?

**Comment by jfmrod** [comment]
MAPseq will not report any result for a sequence if it does not find any hit with an alignment score higher or equal to 30. You can reduce this limit by using the --minscore argument to MAPseq. If you are sure those 200 sequences should match sequences that are found in your database (for example you get a high scoring alignment using another program such as BLAST, usearch or vsearch) then if you can provide me with the reference and query you are using I can investigate it further.
