### ISSUE TITLE
Mac executable

### ISSUE THREAD

**Issue by SilasK** [jfmrod/MAPseq#9]
Hey I wanted to inform you that the link to the mac executable is dead. 

I wanted also to ask if it would be possible to make mapseq installable via bioconda. I can help you, but for this I would need a way to download a binary package for mac or build it on mac.

**Comment by jfmrod** [comment]
Thanks for the heads up.
I've made a osx release for the latest version available on the github releases page:
https://github.com/jfmrod/MAPseq/releases/tag/v1.2.3

Let me know if it works for you. I've also fixed several issues in the build process that I had on mac on the git repo. So compiling it on mac should work better now.

**Comment by SilasK** [comment]
Thank you for the fast replay. 

You may want to provide the executable also on the lab web site. 

However, I got thiss error:
```
dyld: Library not loaded: /opt/local/lib/libcrypto.1.0.0.dylib
  Referenced from: /Users/silas/Desktop/WarmMicrobiota/mapseq-1.2.3-macosx/mapseq
  Reason: image not found
Abort trap: 6

```

my version.
```
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G29

```

**Comment by jfmrod** [comment]
Thanks for the heads up.
I've uploaded a recompiled version (same place https://github.com/jfmrod/MAPseq/releases/tag/v1.2.3) which should solve the problem.
